name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        id: hello-step
        run: echo "Hello, ${{ github.actor }}! Welcome to GitHub Actions."
